### ISSUE TITLE
Error from the start

### ISSUE THREAD

**Issue by epicmario7133** [misterhat/tetrio-bot#2]
sh tetrio.sh 
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn chromium ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Pajsen9263** [comment]
So you don't have chromium installed
